apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: emp-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==    # "root" in base64
  MYSQL_DATABASE: ZW1wbG95ZWVfZGI=  # "employee_db"
  MYSQL_USER: ZW1wbG95ZWVfdXNlcg==  # "employee_user"
  MYSQL_PASSWORD: cm9vdA==          # "root"
