apiVersion: v1               # Core API version for Kubernetes resources like Secret.
kind: Secret                 # Defines this object as a Secret (used to store sensitive data).
metadata:
  name: mysql-secret         # Name of the Secret.
  namespace: emp-app         # Namespace where the Secret will be created.
type: Opaque                 # Secret type. Opaque is generic key-value storage.
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==       # Base64-encoded value for root password ("root").
  MYSQL_DATABASE: ZGVtcGxveWVlX2Ri    # Base64-encoded value for database name ("employee_db").
  MYSQL_USER: ZW1wbG95ZWVfdXNlcg==    # Base64-encoded value for MySQL user ("employee_user").
  MYSQL_PASSWORD: cm9vdA==            # Base64-encoded value for MySQL password ("root").
