apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
spec:
  clusterIP: None          # Headless service
  selector:
    app: mysql             # Must match StatefulSet labels
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
