apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  serviceName: mysql-headless
  replicas: {{ .Values.mysql.replicaCount }}
  
  # Selector must exactly match pod template labels
  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql   # <-- MUST match selector above
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.secrets.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.secrets.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.secrets.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.secrets.password }}
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: init-sql
          configMap:
            name: mysql-initdb
            items:
              - key: init.sql
                path: init.sql

  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mysql.storage.size }}
