apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secrets.rootPassword }}
  MYSQL_DATABASE: {{ .Values.mysql.secrets.database }}
  MYSQL_USER: {{ .Values.mysql.secrets.user }}
  MYSQL_PASSWORD: {{ .Values.mysql.secrets.password }}
