apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: emp-app
spec:
  clusterIP: None           #   mandatory for Headless Service 
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
